language: python

python:
  - 2.7
  - 3.6
  - 3.5
  - 3.4
  - pypy

install:
  - pip install coveralls

script:
  - python setup.py install

after_success:
  - coverage report
  - coveralls

matrix:
  allow_failures:
    - python: 3.6
    - python: 3.5
    - python: 3.4
